apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - services.yaml
  - deployments.yaml
  - hpa.yaml
  - ingress.yaml

